name: Start tests and deploy

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
          - 2181:2181
        options: >-
          --network kafka-network
          --network-alias zookeeper
          --health-cmd "echo ruok | nc localhost 2181 | grep imok"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        kafka:
          image: confluentinc/cp-kafka:7.2.2
          env:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          ports:
            - 29092:29092
            - 9092:9092
          options: >-
            --network kafka-network
            --health-cmd "kafka-topics --bootstrap-server localhost:9092 --list"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Основной шаг загрузки переменных
      - name: Load .env file
        uses: falti/dotenv-action@v1
        with:
          env-file: .env
          override: true

      # Проверка загруженных переменных (опционально)
      - name: Debug env variables
        run: |
          echo "DB_USER: ${{ secrets.DB_USER }}"
          echo "DB_NAME: ${{ secrets.DB_NAME }}"
          echo "KAFKA_TOPIC: ${{ secrets.KAFKA_TOPIC_NAME }}"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install psycopg2-binary redis kafka-python

      - name: Wait for services
        run: sleep 60

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_USER: ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ vars.DB_NAME }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          KAFKA_BOOTSTRAP_SERVERS: localhost:9092
          KAFKA_TOPIC_NAME: ${{ vars.KAFKA_TOPIC_NAME }}
          MODE: TEST
        run: pytest

  build:
    name: Build with Docker Compose
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Load .env for build
        uses: falti/dotenv-action@v2
        with:
          env-file: .env
          override: true

      - name: Docker compose build
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml up -d --wait